MONGODB_HOST: mongodb-{{ env }}.devaws.shop
REDIS_HOST: redis-{{ env }}.devaws.shop
CATALOGUE_HOST: catalogue-{{ env }}.devaws.shop
CART_HOST: cart-{{ env }}.devaws.shop
USER_HOST: user-{{ env }}.devaws.shop
RABBITMQ_HOST: rabbitmq-{{ env }}.devaws.shop
MYSQL_HOST: mysql-{{ env }}.devaws.shop
SHIPPING_HOST: shipping-{{ env }}.devaws.shop
PAYMENT_HOST: payment-{{ env }}.devaws.shop