MONGODB_HOST: mongodb.devaws.shop
REDIS_HOST: redis.devaws.shop
CATALOGUE_HOST: catalogue.devaws.shop
CART_HOST: cart.devaws.shop
USER_HOST: user.devaws.shop
RABBITMQ_HOST: rabbitmq.devaws.shop
MYSQL_HOST: mysql.devaws.shop
SHIPPING_HOST: shipping.devaws.shop
PAYMENT_HOST: payment.devaws.shop