MONGODB_HOST: mongodb-{{ env }}.devaws.shop
REDIS_HOST: redis-{{ env }}.devaws.shop
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.devaws.shop
CART_HOST: cart.backend-alb-{{ env }}.devaws.shop
USER_HOST: user.backend-alb-{{ env }}.devaws.shop
RABBITMQ_HOST: rabbitmq-{{ env }}.devaws.shop
MYSQL_HOST: mysql-{{ env }}.devaws.shop
SHIPPING_HOST: shipping.backend-alb-{{ env }}.devaws.shop
PAYMENT_HOST: payment.backend-alb-{{ env }}.devaws.shop